In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import io
df=pd.read_csv('/content/crop_recommendation.csv')


In [ ]:
df.shape

(2200, 8)

In [ ]:
df.head(5)

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [ ]:
df.tail(5)

N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [ ]:
df.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [ ]:
df.groupby('temperature').size()

temperature
8.825675     1
9.467960     1
9.535586     1
9.724458     1
9.851243     1
            ..
43.037143    1
43.080227    1
43.302049    1
43.360515    1
43.675493    1
Length: 2200, dtype: int64

# Extracting independent variable

In [ ]:
x=df.iloc[:,:-1].values
z=df[["temperature","humidity"]]
y=df.iloc[:,3].values
y=df[["label"]]

# Finding the unique values

In [ ]:
df.humidity.unique()
df.humidity.nunique(dropna=True)


2200

In [ ]:

unique_values = df.nunique()
print(unique_values)


N               137
P               117
K                73
temperature    2200
humidity       2200
ph             2200
rainfall       2200
label            22
dtype: int64


In [ ]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [ ]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [ ]:
df.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label           object
dtype: object

In [ ]:
df['label'].value_counts()

rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: label, dtype: int64

# Finding the missing values

In [ ]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
df.isna().head()
df.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

# Deleting the missing values

In [ ]:
#dropna()
#df_records_dropped = df.dropna(axis=0, how='any',inplace=True)
#df_records_dropped.info()

# Replacing the missing values

In [ ]:
#pandas.df.fillna()
#pandas.df.fillna(100)

# Removing duplicates from the Pandas Data frame

In [ ]:
#DataFrame.drop_duplicates(subset=None, keep=’first’, inplace=False)

In [ ]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [ ]:
features = df[['N', 'P','K','temperature', 'humidity', 'ph', 'rainfall']]
target = df['label']
#features = df[['temperature', 'humidity', 'ph', 'rainfall']]
labels = df['label']

# Encoding Categorical data:

In [ ]:
#from sklearn.preprocessing import LabelEncoder
#label_encoder_x= LabelEncoder()
#x[:, 0]= label_encoder_x.fit_transform(x[:, 0])

# Splitting into train and test data

In [ ]:
# Splitting into train and test data

from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(features,target,test_size = 0.2,random_state =2)

# Feature scaling (Standardization and Normalization)

In [ ]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
Xtrain= st_x.fit_transform(Xtrain)
Xtest= st_x.transform(Xtest)

# Normalization using min max scalar
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler(feature_range=(0, 2))
norm = scaler.fit_transform(Xtrain)
print(norm)
#Normalization using normalize method
norm_data = preprocessing.normalize(Xtrain, axis=0)
#if the value of axis is 1 it will normalize along rows
#if the value of axis is 0 it will normalize along column
print(norm_data)

[[1.61428571 0.47142857 0.2        ... 1.52142102 1.20787222 0.50476888]
 [0.4        0.42857143 0.17       ... 1.69084978 1.13580672 0.28513585]
 [0.15714286 0.8        0.16       ... 0.20419944 0.63055725 0.82768105]
 ...
 [0.32857143 0.48571429 0.17       ... 1.57991719 1.0450731  0.15682462]
 [1.67142857 1.08571429 0.48       ... 1.49185914 0.62294994 0.56015118]
 [0.55714286 0.27142857 0.09       ... 1.78815571 1.14597618 0.61727418]]
[[ 0.04052021 -0.01154883 -0.01112078 ...  0.00870863  0.02868879
  -0.00561396]
 [-0.01447379 -0.01369254 -0.0125029  ...  0.0164482   0.02154573
  -0.01887895]
 [-0.02547259  0.00488628 -0.0129636  ... -0.05146258 -0.02853413
   0.0138887 ]
 ...
 [-0.01770873 -0.01083426 -0.0125029  ...  0.01138075  0.01255229
  -0.02662846]
 [ 0.04310817  0.01917768  0.00177895 ...  0.00735823 -0.02928816
  -0.00226908]
 [-0.00735692 -0.02155281 -0.01618853 ...  0.02089317  0.02255371
   0.00118093]]
